blueprint:
  name: Mushroom Alert Template Card Blueprint
  description:  Mushroom Alert Template card by Michel Jourdain
  version: "1.0"
  type: card
  
  custom_cards:
    - mushroom-template-card
    - card-mod

  input:
  
    01_alert_name:
       name: Alert name
       description: The alert name
       type: text-field
  
    02_alert_entity:
       name: Alert entity
       description: The alert entity
       type: entity-picker
       
    03_alert_icon_off:
       name: Alert icon off, locked...
       description: The alert icon when is OFF
       type: icon-picker
       
    04_alert_icon_on:
       name: Alert icon on, unlocked...
       description: The alert icon when is ON
       type: icon-picker
       
    05_normal_state_translate:
       name: Translate Normale state
       description: Translate The normal state, off, locked...
       type: text-field       
       
    06_alert_state_translate:
       name: Translate Alert state
       description: Translate The alert state, off, locked...
       type: text-field       

    07_normal_state:
       name: Normale state
       description: The normal state, off, locked...
       type: text-field

    08_alert_state:
       name: Alert state
       description: The alert state, on, unlocked...
       type: text-field
       
card:

  type: custom:mushroom-template-card
  primary: $01_alert_name$
  secondary: |-
    {% if is_state('$02_alert_entity$', '$07_normal_state$') %}
        $05_normal_state_translate$
    {% elif is_state('$02_alert_entity$', '$08_alert_state$') %}
        $06_alert_state_translate$
    {% else %}
       {{ states('$02_alert_entity$') }}
    {% endif %}
  icon: |-
    {% if is_state('$02_alert_entity$', '$07_normal_state$') %}
        $03_alert_icon_off$
    {% elif is_state('$02_alert_entity$', '$08_alert_state$') %}
        $04_alert_icon_on$
    {% else %}
       mdi:alert-circle-outline
    {% endif %}
  icon_color: |-
    {% if is_state('$02_alert_entity$', '$07_normal_state$') %}
        green
    {% elif is_state('$02_alert_entity$', '$08_alert_state$') %}
        red
    {% else %}
        yellow
    {% endif %}
  card_mod:
    style: |
      {% if is_state('$02_alert_entity$', '$08_alert_state$') %}
          ha-card {
            animation: borderPulse 2s ease-out infinite;
          }
          @keyframes borderPulse {
          50% {
            box-shadow: 0 0 20px red;
          }
        }
      {% endif %}
