blueprint:
  name: Formula One Blueprint
  description: Formula One Blueprint by Michel Jourdain 
  version: "3.0"
  
  type: page
  
  custom_cards:

    - button-card
    - formulaone-card
    - state-switch

  input:
 
    09_translate_last:
      name: Last in your language
      description: Translate Last Race in your language
      type: text-field 
  
    10_translate_race:
      name: Race in your language
      description: Translate Race in your language
      type: text-field
      
    11_translate_next_race:
      name: Next race in your language
      description: Translate next race in your language
      type: text-field
      
    12_translate_last_result:
      name: Last result in your language
      description: Translate last result in your language
      type: text-field

    13_translate_date:
      name: Date in your language
      description: Translate date in your language
      type: text-field      

    14_translate_practice:
      name: Practice in your language
      description: Translate practice in your language
      type: text-field           
      
    15_translate_race_name:
      name: Race name in your language
      description: Translate Race name in your language
      type: text-field              

    16_translate_circuit_name:
      name: Circuit name in your language
      description: Translate Circuit name in your language
      type: text-field      
      
    17_translate_location:
      name: Location in your language
      description: Translate Location in your language
      type: text-field      

    18_translate_sprint:
      name: Sprint in your language
      description: Translate Sprint in your language
      type: text-field      
      
    19_translate_qualifying:
      name: Qualifying in your language
      description: Translate Qualifying in your language
      type: text-field      

    20_translate_stand:
      name: Stand in your language
      description: Translate stand in your language
      type: text-field
      
    21_translate_drivers_standings:
      name: Drivers standings in your language
      description: Translate drivers standings in your language
      type: text-field
      
    22_translate_constructors_standings:
      name:  Constructors standings in your language
      description: Translate constructor standings in your language
      type: text-field
      
    23_translate_endofseason:
      name:  End of season in your language
      description: Translate End of season in your language
      type: text-field
      
    24_translate_points:
      name:  Points in your language
      description: Translate Points in your language
      type: text-field

    25_translate_driver:
      name:  Driver in your language
      description: Translate Driver in your language
      type: text-field

    26_translate_grid:
      name:  Grid in your language
      description: Translate Grid in your language
      type: text-field
      
    27_translate_status:
      name:  Status in your language
      description: Translate Status in your language
      type: text-field

    28_translate_wins:
      name:  Wins in your language
      description: Translate Wins in your language
      type: text-field
      
    29_translate_team:
      name:  Team in your language
      description: Translate Team in your language
      type: text-field

    30_translate_schedule:
      name: Schedule in your language
      description: Translate Schedule in your language
      type: text-field
      
    31_translate_constructor:
      name: Constructor in your language
      description: Translate Constructor in your language
      type: text-field      
      
    32_translate_time:
      name: Time in your language
      description: Translate Time in your language
      type: text-field      
      
    40_local_contry:
      name: Local contry
      description: Your contry for the race time. Ex, fr, ca, nl..
      type: text-field

card:

  type: custom:dwains-flexbox-card
  items_classes: col-xs-12
  cards:
  - type: vertical-stack
    item_classes: "col-xs-12 col-sm-5"
    cards:

      - type: markdown
        content: "![Image](https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/F1.svg/1280px-F1.svg.png)"

      - card_type: next_race
        date_locale: $40_local_contry$
        image_clickable: false
        sensor: sensor.formula_one_sensor_races
        title: $11_translate_next_race$
        translations: 
          'date' : '$13_translate_date$'  
          'practice1' : '$14_translate_practice$ 1'
          'practice2' : '$14_translate_practice$ 2'
          'practice3' : '$14_translate_practice$ 3'
          'race' : '$10_translate_race$'
          'racename' : '$15_translate_race_name$'
          'circuitname' : '$16_translate_circuit_name$'
          'location' : '$17_translate_location$'
          'racetime' : '$10_translate_race$'
          'sprint' : '$18_translate_sprint$'
          'qualifying' : '$19_translate_qualifying$'
          'endofseason' : '$23_translate_endofseason$ !'
        type: custom:formulaone-card

  - type: vertical-stack
    item_classes: "col-xs-12 col-sm-7"
    cards:

        - type: custom:state-switch
          default: last_race
          entity: hash
          states:
            last_race:
              type: vertical-stack
              cards:
                - type: custom:dwains-flexbox-card
                  padding: true
                  cards:
                    - type: horizontal-stack
                      cards:
                        - name: $09_translate_last$
                          tap_action:
                            action: navigate
                            navigation_path: '#last_race'
                          type: custom:button-card
                          styles:
                            card:
                              - height: 30px
                              - width: 115px                              
                            name:
                              - color: lightblue
                              - font-weight: bold
                              - font-size: 16px
                        - name: $20_translate_stand$
                          tap_action:
                            action: navigate
                            navigation_path: '#stands'
                          type: custom:button-card
                          styles:
                            card:
                              - height: 30px
                              - width: 115px                              
                            name:
                              - font-size: 16px                          
                        - name: $30_translate_schedule$
                          tap_action:
                            action: navigate
                            navigation_path: '#kalender'
                          type: custom:button-card
                          styles:
                            card:
                              - height: 30px
                              - width: 115px                              
                            name:
                              - font-size: 16px                             
                - card_type: last_result
                  sensor: sensor.formula_one_sensor_last_result
                  title: $12_translate_last_result$
                  translations: 
                    'points' : '$24_translate_points$'
                    'driver' : '$25_translate_driver$'
                    'grid' : '$26_translate_grid$'  
                    'status' : '$27_translate_status$'
                  type: custom:formulaone-card

            stands:
              type: vertical-stack
              cards:
                - type: custom:dwains-flexbox-card
                  padding: true
                  cards:
                    - type: horizontal-stack
                      cards:
                        - name: $09_translate_last$
                          tap_action:
                            action: navigate
                            navigation_path: '#last_race'
                          type: custom:button-card
                          styles:
                            card:
                              - height: 30px
                              - width: 115px                              
                            name:
                              - font-size: 16px                             
                        - name: $20_translate_stand$
                          styles:
                            card:
                              - height: 30px
                              - width: 115px                              
                            name:
                              - color: lightblue
                              - font-weight: bold
                              - font-size: 16px
                          tap_action:
                            action: navigate
                            navigation_path: '#stands'
                          type: custom:button-card
                        - name: $30_translate_schedule$
                          tap_action:
                            action: navigate
                            navigation_path: '#kalender'
                          type: custom:button-card
                          styles:
                            card:
                              - height: 30px
                              - width: 115px                              
                            name:
                              - font-size: 16px                             
                - card_type: driver_standings
                  sensor: sensor.formula_one_sensor_drivers
                  title: $21_translate_drivers_standings$
                  standings:
                    show_flag: true
                    show_team: true
                  translations: 
                    'points' : '$24_translate_points$'
                    'wins' : '$28_translate_wins$'
                    'team' : '$29_translate_team$'
                    'driver' : '$25_translate_driver$'
                  type: custom:formulaone-card
                - card_type: constructor_standings
                  sensor: sensor.formula_one_sensor_constructors
                  title: $22_translate_constructors_standings$
                  translations: 
                    'constructor' : '$31_translate_constructor$'
                    'points' : '$24_translate_points$'
                    'wins' : '$28_translate_wins$'
                  type: custom:formulaone-card

            kalender:
              type: vertical-stack
              cards:
                - type: custom:dwains-flexbox-card
                  padding: true
                  cards:
                    - type: horizontal-stack
                      cards:
                        - name: $09_translate_last$
                          tap_action:
                            action: navigate
                            navigation_path: '#last_race'
                          type: custom:button-card
                          styles:
                            card:
                              - height: 30px
                              - width: 115px                              
                            name:
                              - font-size: 16px                             
                        - name: $20_translate_stand$
                          tap_action:
                            action: navigate
                            navigation_path: '#stands'
                          type: custom:button-card
                          styles:
                            card:
                              - height: 30px
                              - width: 115px                              
                            name:
                              - font-size: 16px                             
                        - name: $30_translate_schedule$
                          styles:
                            card:
                              - height: 30px
                              - width: 115px                              
                            name:
                              - color: lightblue
                              - font-weight: bold
                              - font-size: 16px
                          tap_action:
                            action: navigate
                            navigation_path: '#kalender'
                          type: custom:button-card
                - card_type: schedule
                  date_locale: $40_local_contry$
                  sensor: sensor.formula_one_sensor_races
                  title: $30_translate_schedule$
                  translations: 
                    'date' : '$13_translate_date$'
                    'race' : '$10_translate_race$'
                    'location' : '$17_translate_location$$'
                    'endofseason' : '$23_translate_endofseason$ !'
                    'time' : '$32_translate_time$'
                  type: custom:formulaone-card 
