blueprint:
  name: Formula One Blueprint
  description: Formula One Blueprint by Michel Jourdain
  version: "1.0"
  
  type: page
  
  custom_cards:

    - button-card
    - formulaone-card

  input:
  
    10_translate_race:
      name: Race un your language
      description: Translate race in your language
      type: text-field
      
    11_translate_next_race:
      name: Next race in your language
      description: Translate next race in your language
      type: text-field
      
    12_translate_last_result:
      name: Last result in your language
      description: Translate last result in your language
      type: text-field
      
    20_translate_stand:
      name: Stand in your language
      description: Translate stand in your language
      type: text-field
      
    21_translate_drivers_standings:
      name: Drivers standings in your language
      description: Translate drivers standings in your language
      type: text-field
      
    22_translate_constructors_standings:
      name:  Constructors standings un your language
      description: Translate constructor standings in your language
      type: text-field
      
    30_translate_schedule:
      name: Schedule un your language
      description: Translate schedule in your language
      type: text-field
      
    40_local_contry:
      name: Local contry
      description: Your contry for the race time. Ex, fr, ca, nl..
      type: text-field

card:

  type: custom:dwains-flexbox-card
  items_classes: 'col-xs-12'
  cards:
    - type: vertical-stack
      item_classes: 'col-xs-12 col-sm-6'
      cards:         
         
          - type: custom:state-switch
            entity: hash
            default: page01
            states:
              page01:
                type: vertical-stack
                cards:
                  - type: custom:dwains-flexbox-card
                    padding: true
                    cards:
                      - type: horizontal-stack
                        cards:
                                 
                          - type: custom:button-card
                            name: $10_translate_race$
                            template: button_card_templates_race_heading
                            tap_action: 
                              action: navigate
                              navigation_path: "#page01"
                            styles:
                              name:
                                 - color: lightgreen
                          - type: custom:button-card
                            name: $20_translate_stand$
                            template: button_card_templates_race_heading
                            tap_action: 
                              action: navigate
                              navigation_path: "#page02"
                          - type: custom:button-card
                            name: $30_translate_schedule$
                            template: button_card_templates_race_heading
                            tap_action: 
                              action: navigate
                              navigation_path: "#page03"

                  - type: custom:formulaone-card
                    card_type: next_race
                    sensor: sensor.formula_one_sensor_races
                    title: $11_translate_next_race$
                    date_locale: $40_local_contry$
                    image_clickable: false
 
              page02:
                type: vertical-stack
                cards:
                  - type: custom:dwains-flexbox-card
                    padding: true
                    cards:
                      - type: horizontal-stack
                        cards:
                                 
                          - type: custom:button-card
                            name: $10_translate_race$
                            template: button_card_templates_race_heading
                            tap_action: 
                              action: navigate
                              navigation_path: "#page01"
                          - type: custom:button-card
                            name: $20_translate_stand$
                            template: button_card_templates_race_heading
                            tap_action: 
                              action: navigate
                              navigation_path: "#page02"
                            styles:
                              name:
                                 - color: lightgreen
                          - type: custom:button-card
                            name: $30_translate_schedule$
                            template: button_card_templates_race_heading
                            tap_action: 
                              action: navigate
                              navigation_path: "#page03"
                
                  - type: custom:formulaone-card
                    card_type: driver_standings
                    sensor: sensor.formula_one_sensor_drivers
                    title: $21_translate_drivers_standings$
                          
              page03:
                type: vertical-stack
                cards:
                  - type: custom:dwains-flexbox-card
                    padding: true
                    cards:
                      - type: horizontal-stack
                        cards:
                          - type: custom:button-card
                            name: $10_translate_race$
                            template: button_card_templates_race_heading
                            tap_action: 
                              action: navigate
                              navigation_path: "#page01"
                          - type: custom:button-card
                            name: $20_translate_stand$
                            template: button_card_templates_race_heading
                            tap_action: 
                              action: navigate
                              navigation_path: "#page02"
                          - type: custom:button-card
                            name: $30_translate_schedule$
                            template: button_card_templates_race_heading
                            tap_action: 
                              action: navigate
                              navigation_path: "#page03"
                            styles:
                              name:
                                 - color: lightgreen
                                 
                  - type: markdown
                    content: >
                     ![Image](https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/F1.svg/1280px-F1.svg.png)
                          
    - type: vertical-stack
      item_classes: 'col-xs-12 col-sm-6'
      cards:         
 
          - type: custom:state-switch
            entity: hash
            default: page01
            states:
            
              page01:
                type: vertical-stack
                cards:
                
                  - type: 'custom:button-card'
                    color_type: blank-card
                    template: button_card_templates_race_space
                       
                  - type: custom:formulaone-card
                    card_type: last_result
                    sensor: sensor.formula_one_sensor_last_result
                    title: $12_translate_last_result$

                    
              page02:
                type: vertical-stack
                cards:
                  - type: 'custom:button-card'
                    color_type: blank-card
                    template: button_card_templates_race_space
                       
                  - type: custom:formulaone-card
                    card_type: constructor_standings
                    sensor: sensor.formula_one_sensor_constructors
                    title: $22_translate_constructors_standings$
                    
              page03:
                type: vertical-stack
                cards:
                  - type: 'custom:button-card'
                    color_type: blank-card
                    template: button_card_templates_race_space
                                 
                  - type: custom:formulaone-card
                    card_type: schedule
                    sensor: sensor.formula_one_sensor_races
                    title: $30_translate_schedule$
                    date_locale: $40_local_contry$


button_card_templates:
  button_card_templates_race_heading:
    show_icon: false
    styles:
      card:
      - box-shadow: none
      - padding: 6px 0 0 0
      - background: transparent
      - width: 100px
      name:
      - font-weight: bold
      - justify-self: start
      - font-size: 16px
      - padding-left: 1px

  button_card_templates_race_space:
    show_icon: false
    styles:
      card:
      - box-shadow: none
      - padding: 6px 0 0 0
      - background: transparent
      - height: 59px
