blueprint:
  name: Formula One Blueprint
  description: Formula One Blueprint by Michel Jourdain 
  version: "2.0"
  
  type: page
  
  custom_cards:

    - button-card
    - formulaone-card
    - state-switch

  input:
  
    10_translate_last:
      name: Race in your language
      description: Translate last (from last race) in your language
      type: text-field
      
    11_translate_next_race:
      name: Next race in your language
      description: Translate next race in your language
      type: text-field
      
    12_translate_last_result:
      name: Last result in your language
      description: Translate last result in your language
      type: text-field
      
    20_translate_stand:
      name: Stand in your language
      description: Translate stand in your language
      type: text-field
      
    21_translate_drivers_standings:
      name: Drivers standings in your language
      description: Translate drivers standings in your language
      type: text-field
      
    22_translate_constructors_standings:
      name:  Constructors standings in your language
      description: Translate constructor standings in your language
      type: text-field
      
    30_translate_schedule:
      name: Schedule in your language
      description: Translate schedule in your language
      type: text-field
      
    40_local_contry:
      name: Local contry
      description: Your contry for the race time. Ex, fr, ca, nl..
      type: text-field

card:

  type: custom:dwains-flexbox-card
  items_classes: col-xs-12
  cards:
  - type: vertical-stack
    item_classes: "col-xs-12 col-sm-5"
    cards:

      - type: markdown
        content: "![Image](https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/F1.svg/1280px-F1.svg.png)"

      - card_type: next_race
        date_locale: $40_local_contry$
        image_clickable: false
        sensor: sensor.formula_one_sensor_races
        title: $11_translate_next_race$
        type: custom:formulaone-card

  - type: vertical-stack
    item_classes: "col-xs-12 col-sm-7"
    cards:

        - type: custom:state-switch
          default: last_race
          entity: hash
          states:
            last_race:
              type: vertical-stack
              cards:
                - type: custom:dwains-flexbox-card
                  padding: true
                  cards:
                    - type: horizontal-stack
                      cards:
                        - name: $10_translate_last$
                          tap_action:
                            action: navigate
                            navigation_path: '#last_race'
                          type: custom:button-card
                          styles:
                            card:
                              - height: 30px
                              - width: 115px                              
                            name:
                              - color: lightblue
                              - font-weight: bold
                              - font-size: 16px
                        - name: $20_translate_stand$
                          tap_action:
                            action: navigate
                            navigation_path: '#stands'
                          type: custom:button-card
                          styles:
                            card:
                              - height: 30px
                              - width: 115px                              
                            name:
                              - font-size: 16px                          
                        - name: $30_translate_schedule$
                          tap_action:
                            action: navigate
                            navigation_path: '#kalender'
                          type: custom:button-card
                          styles:
                            card:
                              - height: 30px
                              - width: 115px                              
                            name:
                              - font-size: 16px                             
                - card_type: last_result
                  sensor: sensor.formula_one_sensor_last_result
                  title: $12_translate_last_result$
                  type: custom:formulaone-card

            stands:
              type: vertical-stack
              cards:
                - type: custom:dwains-flexbox-card
                  padding: true
                  cards:
                    - type: horizontal-stack
                      cards:
                        - name: $10_translate_last$
                          tap_action:
                            action: navigate
                            navigation_path: '#last_race'
                          type: custom:button-card
                          styles:
                            card:
                              - height: 30px
                              - width: 115px                              
                            name:
                              - font-size: 16px                             
                        - name: $20_translate_stand$
                          styles:
                            card:
                              - height: 30px
                              - width: 115px                              
                            name:
                              - color: lightblue
                              - font-weight: bold
                              - font-size: 16px
                          tap_action:
                            action: navigate
                            navigation_path: '#stands'
                          type: custom:button-card
                        - name: $30_translate_schedule$
                          tap_action:
                            action: navigate
                            navigation_path: '#kalender'
                          type: custom:button-card
                          styles:
                            card:
                              - height: 30px
                              - width: 115px                              
                            name:
                              - font-size: 16px                             
                - card_type: driver_standings
                  sensor: sensor.formula_one_sensor_drivers
                  title: $21_translate_drivers_standings$
                  type: custom:formulaone-card
                - card_type: constructor_standings
                  sensor: sensor.formula_one_sensor_constructors
                  title: $22_translate_constructors_standings$
                  type: custom:formulaone-card

            kalender:
              type: vertical-stack
              cards:
                - type: custom:dwains-flexbox-card
                  padding: true
                  cards:
                    - type: horizontal-stack
                      cards:
                        - name: $10_translate_last$
                          tap_action:
                            action: navigate
                            navigation_path: '#last_race'
                          type: custom:button-card
                          styles:
                            card:
                              - height: 30px
                              - width: 115px                              
                            name:
                              - font-size: 16px                             
                        - name: $20_translate_stand$
                          tap_action:
                            action: navigate
                            navigation_path: '#stands'
                          type: custom:button-card
                          styles:
                            card:
                              - height: 30px
                              - width: 115px                              
                            name:
                              - font-size: 16px                             
                        - name: $30_translate_schedule$
                          styles:
                            card:
                              - height: 30px
                              - width: 115px                              
                            name:
                              - color: lightblue
                              - font-weight: bold
                              - font-size: 16px
                          tap_action:
                            action: navigate
                            navigation_path: '#kalender'
                          type: custom:button-card
                - card_type: schedule
                  date_locale: $40_local_contry$
                  sensor: sensor.formula_one_sensor_races
                  title: $30_translate_schedule$
                  type: custom:formulaone-card     
