blueprint:
  name: Thermostat and A/C card Blueprint
  description: Thermostat and A/C card by Michel Jourdain
  version: "1.1"
  type: card
  
  custom_cards:
    - simple-thermostat

  input:
  
    01_Thermostat_name:
       name: Thermostat name
       description: Thermostat name
       type: text-field
  
    02_thermostat_entity:
       name: Thermostat entity
       description: The thermostat entity
       type: entity-picker
       
    03_thermostat_controls_buttons_hide_show:
       name: Controls hide
       description: Controls hide
       type: checkbox
       default_value: false
       
    04_thermostat_controls_names_hide_show:
       name: If Controls are activated name hide
       description: If Controls are activated name hide
       type: checkbox
       default_value: false
       
    05_thermostat_controls_icons_hide_show:
       name: If Controls are activated icon hide
       description: If Controls are activated icon hide
       type: checkbox
       default_value: false
       
    06_thermostat_controls_heading_hide_show:
       name: If Controls are activated heading hide
       description: If Controls are activated heading hide
       type: checkbox
       default_value: false
       
    07_thermostat_temperature_hide_show:
       name: Temperature hide
       description: Hide temperature
       type: checkbox
       default_value: false

    08_thermostat_state_hide_show:
       name: State hide
       description: Hide state
       type: checkbox
       default_value: false
       
    09_thermostat_sensors_label_hide_show:
       name: If sensors are activated hide label
       description: If the sensors are activated hide sensors label
       type: checkbox
       default_value: false

card:

  type: custom:dwains-flexbox-card
  items_classes: 'col-xs-12'
  cards:

    - type: custom:simple-thermostat
      entity: $02_thermostat_entity$
      header:
        name:  $01_Thermostat_name$
      control: $03_thermostat_controls_buttons_hide_show$
      layout:
        step: column
        mode:
          names: $04_thermostat_controls_names_hide_show$
          icons: $05_thermostat_controls_icons_hide_show$
          headings: $06_thermostat_controls_heading_hide_show$
        sensors:
          labels: $09_thermostat_sensors_label_hide_show$
      hide:
        temperature: $07_thermostat_temperature_hide_show$
        state: $08_thermostat_state_hide_show$
        
        
        
        